### ISSUE TITLE
[구독 신청] 이메일 알림 구독 신청

### ISSUE THREAD

**Issue by essaysir** [project-notification/readme#18]
### 알림을 받을 이메일 주소를 입력해주세요.

sonjs7554@naver.com

### 알림을 받을 항목를 선택해주세요.

- [X] 프론트
- [ ] 백엔드
- [ ] 기획
- [ ] 디자인
- [ ] 마케팅
- [ ] PM

**Comment by leemhoon00** [comment]
죄송합니다. sqs 배치 사이즈 관련 에러가 있어서 미전송된 알림이 몇개있습니다. 현재 수정완료해서 이제는 문제없을겁니다!
